---
title: rent-e-motion
author: Timur
email: info@rent-e-motion.de
description: rent-e-motion site developed using a Jekyll theme. This page is the bone
  of rent-e-motion company page.
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
